version: '3.7'

services:
  fit-feed:
    container_name: fit-feed
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  db:
    image: mysql:latest
    container_name: mysql-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: FITFEED_USER
      MYSQL_PASSWORD: fitfeed
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: zxc258zxc258
  