create table USER_INFO(
	idx MEDIUMINT UNSIGNED AUTO_INCREMENT,
    id VARCHAR(32) UNIQUE NOT NULL,
    passwd BLOB,
    nickname VARCHAR(20),
    data TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (idx)
)